### ISSUE TITLE
StockpileManageUISide.StashHistory is not thread safe

### ISSUE THREAD

**Issue by scowalt** [redscientistlabs/RTCV#221]
https://github.com/redscientistlabs/RTCV/blob/506/Source/Libraries/CorruptCore/Stockpile/StockpileManagerUISide.cs#L34

```
public static volatile List<StashKey> StashHistory = new List<StashKey>();
```

The field is currently marked as [`volatile`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/volatile) to indicate that the value may change on multiple threads. However, `StashHistory` is never re-assigned. My guess is that the intention was to have the `List` itself be thread-safe. However, in order to do that, we would have to use [a thread-safe collection](https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/)

**Comment by NarryG** [comment]
There's a chunk of these in there. Netcore thread safety is something on my very long list of things to evaluate because it uses the thread pool to handle messages. A lot of the code just invokes back onto the main thread before touching certain things which eliminates this from being an issue, but it's not a good way to do it. Once the doevents-hack-fix branch is merged,  I think some of the thread safety issues that exist but haven't caused issues may surface.

**Comment by ircluzar** [comment]
This is a leftover of old bad design. Volatile only ensures the list itself is threadsafe and not its contents. We never had a thread collision occuring with the stash history, the volatile keyword is completely useless and will be removed.

**Comment by ircluzar** [comment]
note: i'm the one who originally put the volatile keyword
