### ISSUE TITLE
[Feature Request] MIDI support

### ISSUE THREAD

**Issue by Sudospective** [redscientistlabs/RTCV#346]
I was rewatching some of Vinesauce Vinny's hardware corruption videos, where he used knobs on a specially modified console to corrupt in real-time. That struck me with an idea; what about MIDI support to mimic the same effect? I'd love to use knobs and buttons on my MIDI controller to change values on the fly rather than manually editing values with a keyboard. Is there any way to implement this feature?

**Comment by ircluzar** [comment]
Hi, using knobs wouldn't really make it work like the hadware corruptor but first of all I think I should explain to you why the Hardware Nes Corruptor used knobs in the first place. 

You see, the Hardware Nes Corruptor is not a digital corruptor. it doesn't work by replacing data in the memory like a we do when we corrupt roms or memory in real-time, you could consider it as an Analog Corruptor or a Circuit Bending machine. In fact, the reason why the Hardware Nes Corruptor works with knobs is because these knobs are in fact attached to serially-linked dynamic resistors. The principle behind this is that you would use the probes in combination with the exposed chip pins via the IDE interfaces and short circuits pins together. A perfect short circuit in most cases will completely crash the game, which is not what we want to achieve when corrupting a videogame. Introducing resistance into the mix can prevent crashes but also it can prevent any effect from happenning if the resistance is too high. Because of that, dynamic resistors are used, a 100omh, 1kohm and a 50 kohm. When serially linked, these three dynamic resistors can let you find the thin area between "crash" and "no effect". When you'd find this zone, you can then obtain weird effects similar to what you'd get on an emulator and sometimes completely new effects that were never seen before via digital methods.

Now that this is out of the way, you can understand why adding knob support for the sake of knob support wouldn't inherently give new effects. In fact, the best thing you could do using knobs via midi would be controlling the many values that the real-time corruptor supports such as the Intensity, error delay, maximum infinite units, etc. These values are already configurable via hotkeys in the settings so if you were to use a software to translate those knobs into repeating key presses, you'd get this behavior without the need of doing any edit to RTC.

It should be worth mentionning that if you wanted native midi support in RTC to control the various settings, you could have it made into a plugin using NetCore commands through the LocalNetCoreRouter system. There are various C# libraries supporting midi support so i don't think this would be too much of a hassle if you know how to write C#. We do have a plugin template available on the git repo and if you intend to take this challenge, please visit us on the discord and we can help you with our (unfortunately) pooly documented API.

Hope that answers your questions !

Cheers,
-Phil
